-- Add additional fields to profiles table for KIN and additional details
ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS kin_full_name text,
ADD COLUMN IF NOT EXISTS kin_relationship text,
ADD COLUMN IF NOT EXISTS kin_phone text,
ADD COLUMN IF NOT EXISTS kin_email text,
ADD COLUMN IF NOT EXISTS kin_address text,
ADD COLUMN IF NOT EXISTS postal_address text,
ADD COLUMN IF NOT EXISTS email text,
ADD COLUMN IF NOT EXISTS occupation text,
ADD COLUMN IF NOT EXISTS employer text,
ADD COLUMN IF NOT EXISTS tax_number text,
ADD COLUMN IF NOT EXISTS citizenship text,
ADD COLUMN IF NOT EXISTS country_of_residence text,
ADD COLUMN IF NOT EXISTS city text,
ADD COLUMN IF NOT EXISTS first_name text,
ADD COLUMN IF NOT EXISTS middle_name text,
ADD COLUMN IF NOT EXISTS last_name text,
ADD COLUMN IF NOT EXISTS id_document_type text,
ADD COLUMN IF NOT EXISTS institution_type text,
ADD COLUMN IF NOT EXISTS is_legal boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS is_foreign boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS is_underage boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS bic_of_investors_bank text,
ADD COLUMN IF NOT EXISTS name_of_investors_bank text,
ADD COLUMN IF NOT EXISTS branch_code text,
ADD COLUMN IF NOT EXISTS branch_name text,
ADD COLUMN IF NOT EXISTS beneficiary_account text,
ADD COLUMN IF NOT EXISTS beneficiary_name text,
ADD COLUMN IF NOT EXISTS dividend_payment_option text,
ADD COLUMN IF NOT EXISTS investor_code text;